### ISSUE TITLE
apiv2/app/buildInfo  一直提示 `App is being processed. Please call this API later to get the information`

### ISSUE THREAD

**Issue by Nicolasking007** [PGYER/upload-app-api-example#10]
apiv2/app/buildInfo  一直提示 `App is being processed. Please call this API later to get the information`

```
{
    "code": 1247,
    "message": "App is being processed. Please call this API later to get the information"
}
```

**Comment by Nicolasking007** [comment]
我丢~    包有问题  估计你们解析不了   所以......     哈哈哈

**Comment by shishirui** [comment]
如果是换了一个安装包就可以了的话，那说明可能确实是包的问题。可以把有问题的包传上来，我们试一下看看。

**Comment by Nicolasking007** [comment]
https://t.wss.ink/f/94dlglr4qb9  复制链接到浏览器打开

**Comment by shishirui** [comment]
我测试了，没问题，可以正常传。你要不用我们的脚本试试？
https://github.com/PGYER/pgyer_api_example/tree/main/shell-demo

**Comment by Nicolasking007** [comment]
有没有Python示例

**Comment by shishirui** [comment]
暂时还没有，我们公司没有人会写 python。

不过，如果需要的话，我可以去学。

**Comment by Nicolasking007** [comment]
> 暂时还没有，我们公司没有人会写 python。
> 
> 不过，如果需要的话，我可以去学。

哈哈哈    兄弟 牛逼    算了 我自己写吧（想用现成的）

**Comment by shishirui** [comment]
> > 暂时还没有，我们公司没有人会写 python。
> > 不过，如果需要的话，我可以去学。
> 
> 哈哈哈 兄弟 牛逼 算了 我自己写吧（想用现成的）

好的 Thanks♪(･ω･)ﾉ
