### ISSUE TITLE
体验槽点

### ISSUE THREAD

**Issue by Nicolasking007** [PGYER/upload-app-api-example#12]
免费产品加点广告大家都能理解，但是蒲公英作为APP内测分发平台，在APP下载成功后用“下载领福利”打广告就不厚道了，用户会误以为是APP厂家本身做的广告，万一广告内容有点流氓用户来谩骂，这就让APP开发者给蒲公英平台背了黑锅，这太不厚道了。

希望开发传达一下建议给产品经理 

![image](https://user-images.githubusercontent.com/45583166/187169102-34157a00-0083-4854-8ec7-ef3dad81ba3c.png)

**Comment by shishirui** [comment]
好的，我们会督促第三方广告联盟去改进，谢谢
