### ISSUE TITLE
buildDescription 换行丢失

### ISSUE THREAD

**Issue by y500** [PGYER/upload-app-api-example#15]
上传的buildDescription里面是有换行符的，但是在下载页面确没有，变成一个长串了

**Comment by shishirui** [comment]
`buildUpdateDescription` 里面只要加上 `\n` 换行就行，我测试后没问题，可以正常换行

**Comment by sunzhongliangde** [comment]
@shishirui 我试过也不行，加了`\n`在下载页面就直接展示`\n`了

变量：
LATEST_COMMIT="$(git log --format="%H" -n 1)"
TIMESTAMP="$(env TZ=Asia/Shanghai date "+%Y-%m-%d %H-%M-%S")"

上传脚本：
`-d " packagetime: ${TIMESTAMP}\n commit:\n${LATEST_COMMIT}" \`
