### ISSUE TITLE
超时也做个判断吧

### ISSUE THREAD

**Issue by emodeqidao** [PGYER/upload-app-api-example#16]
pgyer_upload.sh

超时也报错 也会往下走，会走查询
建议加个超时报错的拦截判断

**Comment by shishirui** [comment]
> pgyer_upload.sh
> 
> 超时也报错 也会往下走，会走查询 建议加个超时报错的拦截判断

请问是哪一步超时了？

**Comment by emodeqidao** [comment]
> > pgyer_upload.sh
> > 超时也报错 也会往下走，会走查询 建议加个超时报错的拦截判断
> 
> 请问是哪一步超时了？

上传的时候，有时候超时了，也会直接走一下步，往查询里面走轮询

**Comment by shishirui** [comment]
代码中有判断，你用最新版本试试
