### ISSUE TITLE
更新详情拼接中文无效

### ISSUE THREAD

**Issue by xypeng12345** [PGYER/upload-app-api-example#17]
-d 后面跟中文参数，上传成功后无更新说明，
中英文混杂上传，中文消失。
![image](https://user-images.githubusercontent.com/21303282/195014932-4e772b56-64bc-4aeb-8df9-e7a86d1e0185.png)
![image](https://user-images.githubusercontent.com/21303282/195014950-12f798d9-0a1d-4649-bab0-476e1ebd9a3f.png)

**Comment by shishirui** [comment]
你用最新版本的 shell demo 中的 -d 参数试一下，我试过了，没问题的。

例如：

    ./pgyer_upload.sh -k xxxxxxxxxxxxxxxxxxxxxxxxx -d "测试 test" 1.ipa
