### ISSUE TITLE
shell上传demo中命令行如何显示上传进度

### ISSUE THREAD

**Issue by AndroidLMY** [PGYER/upload-app-api-example#19]
shell上传demo中命令行如何显示上传进度

**Comment by shishirui** [comment]
在 shell-demo/pgyer_upload.sh 文件中的 121 行附近，找到：

    execCommand "curl -s -o /dev/null -w '%{http_code}' \

改成

    execCommand "curl --progress-bar -o /dev/null -w '%{http_code}' \

就可以了。

@AndroidLMY

**Comment by AndroidLMY** [comment]
高的多谢

**Comment by Yanglmunix** [comment]
使用脚本上传，怎么获取这个值 ${buildQRCodeURL}

**Comment by AndroidLMY** [comment]
> 使用脚本上传，怎么获取这个值 ${buildQRCodeURL}
你可以使用 jq 解析 json 来读取这个值
