### ISSUE TITLE
能否增加一个.net的上传示例  

### ISSUE THREAD

**Issue by FingerCaster** [PGYER/upload-app-api-example#20]

**Comment by shishirui** [comment]
我们这边没人会写 .net ，所以恐怕短时间内是提供不了了

**Comment by 960208781** [comment]
我也在找这个, 目前用的是postman生成的脚本进行测试的, 但是会提示错误, 老版本的上传方式就没问题

**Comment by shishirui** [comment]
> 我也在找这个, 目前用的是postman生成的脚本进行测试的, 但是会提示错误, 老版本的上传方式就没问题

那你可以暂时先用老版本，老版本API目前没有下线计划
