### ISSUE TITLE
希望支持描述换行

### ISSUE THREAD

**Issue by Hanniballol** [PGYER/upload-app-api-example#22]
-d 希望支持换行

**Comment by shishirui** [comment]
已经支持，请更新代码即可。具体可见：https://github.com/PGYER/pgyer_api_example/commit/d597672c3d26337d9b916906528ea9895f7e8ba6

**Comment by Hanniballol** [comment]
又不行了，$n也不识别了，你们h5发了版本？

**Comment by Hanniballol** [comment]
@shishirui

**Comment by shishirui** [comment]
@Hanniballol 我刚测试试过，没问题的，我们h5也没改。我的测试代码如下：

```
./pgyer_upload.sh -k xxxxxxxx -d "aaa\n bbb" ./1.ipa
```

你再试试

**Comment by Hanniballol** [comment]
我之前用的$n可行，改改看

**Comment by Hanniballol** [comment]
`if [ -z "$commitId" ]; then
  dis=$(git log -3 --pretty=format:'%h -%d %s (%ci) <%an>  /n' --abbrev-commit --date=relative)
else
  dis=$(git log --pretty=format:'%h -%d %s (%ci) <%an>  /n' --abbrev-commit --date=relative $commitId..)
fi

if ./pgyer_upload.sh -k $API_KEY -d "$dis" $assembleApk ; then
  lastCommitId $(git rev-parse HEAD)
fi


`

感觉是转义了

**Comment by Hanniballol** [comment]
@shishirui

**Comment by shishirui** [comment]
换行符应该使用 `\n` 而不是其他的

**Comment by Hanniballol** [comment]
sorry
