### ISSUE TITLE
什么时候可以出个gradle脚本？

### ISSUE THREAD

**Issue by LiWeiQiangAndroid** [PGYER/upload-app-api-example#23]
def getPgyCOSToken() {
    def url = new URL('https://www.pgyer.com/apiv2/app/getCOSToken')

    def conn = url.openConnection() as HttpURLConnection
    conn.setRequestMethod('POST')
    conn.setRequestProperty('Content-Type', 'application/json')
    conn.setRequestProperty("Charset", "UTF-8")
    conn.setDoOutput(true)

    def log = getGitVersion()

    def params = new HashMap<>()
    //(必填) API Key 点击获取_api_key
    params.put("_api_key", apikes["pgyerApikey"])
    //(必填) 需要上传的应用类型，如果是iOS类型请传ios或ipa，如果是Android类型请传android或apk
    params.put("buildType", 'android')
    //(选填) 是否使用海外加速上传，值为：1 使用海外加速上传，2 国内加速上传；留空根据 IP 自动判断海外加速或国内加速
    params.put("oversea", 2)
    //(选填)应用安装方式，值为(1,2,3，默认为1 公开安装)。1：公开安装，2：密码安装，3：邀请安装
//    params.put("buildInstallType",1)
    //(选填) 应用介绍，如没有介绍请传空字符串，或不传。
//    params.put("buildPassword","万顺车主")
    //(选填) 版本更新描述，请传空字符串，或不传。
    params.put("buildDescription", log)
    //(选填)是否设置安装有效期，值为：1 设置有效时间， 2 长期有效，如果不填写不修改上一次的设置
    params.put("buildInstallDate", 2)
    //(选填)安装有效期开始时间，字符串型，如：2023-05-31
//    params.put("buildInstallStartDate","2023-05-31")
    //(选填)安装有效期结束时间，字符串型，如：2023-12-31
//    params.put("buildInstallEndDate","2023-12-31")
    //(选填)所需更新指定的渠道短链接，渠道短链接须为已创建成功的，并且只可指定一个渠道，字符串型，如：abcd
//    params.put("buildChannelShortcut","wsjcdriver")

//    def data = [param1: 'value1', param2: 'value2']
    //map 转json
    def outputData = new groovy.json.JsonBuilder(params).toString()
    println(outputData)

    // 输出请求参数
    def outStream = new OutputStreamWriter(conn.outputStream, "UTF-8")
    outStream.write(outputData)
    outStream.flush()
    outStream.close()

    def json = new JsonSlurper()
    def result = json.parseText(conn.content.text)

    println '#########################################################################################################################################'
    println(result)

//    def responseCode = conn.responseCode
//    def responseMessage = conn.responseMessage
//    def responseBody = conn.inputStream.text
//    println "Response code: $responseCode"
//    println "Response message: $responseMessage"
//    println "Response body: $responseBody"
}

{"_api_key":"xxxxxxxxxx","buildType":"android","buildInstallDate":2,"buildDescription":"a16b0ab2","oversea":2}

//一直报这个错误
{code=1001, message=_api_key could not be empty}

明明传了_api_key

**Comment by shishirui** [comment]
https://github.com/ihrthk/pgyer
https://github.com/dodocat/pgyer

你试试这两个行不行
