### ISSUE TITLE
Ktor 上传文件,报错 400

### ISSUE THREAD

**Issue by PostLiu** [PGYER/upload-app-api-example#24]
<img width="1512" alt="image" src="https://github.com/PGYER/upload-app-api-example/assets/28628369/8821a414-8cfa-46b8-9259-1629f73214f4">

**Comment by BlueSky15171** [comment]
遇到同样的问题，旧版Api和新版Api代码一样，新版就无法上传。一直The body of your POST request is not well-formed multipart/form-data.

**Comment by shishirui** [comment]
Ktor 我没有用过，但是只要能发送正常 HTTP 请求应该都是可以的，请检查下你在发送 HTTP 请求时的格式和协议是否正确。同时，建议可以对照 postman 来做调试：https://www.postman.com/pgyerdevs/workspace/pgyer-api

另外，如果实在调试不通，用旧版 API 也是可以的，我们目前还没有移除旧版 API 的计划。
