### ISSUE TITLE
建议开放前端直传

### ISSUE THREAD

**Issue by machengwei1024** [PGYER/upload-app-api-example#25]
建议开放前端直传，允许跨域。比如自己做了app上传站点（vue）。原因是大部分应用服务器的带宽不是很高。

“获取上传的token”这一步可以自己后端调用蒲公英的接口生成，第二步的上传步骤最好支持前端直传，蒲公英返回的endpoint应该是动态的，走vue代理好像是不可行的。

**Comment by shishirui** [comment]
你好，本来就是支持直传的，可以参考 nodejs-demo 代码，可以直接用在前端的：https://github.com/PGYER/upload-app-api-example/tree/main/nodejs-demo
