### ISSUE TITLE
希望增加C#语言的请求示例,尝试了一天都不行

### ISSUE THREAD

**Issue by 960208781** [PGYER/upload-app-api-example#32]

**Comment by shishirui** [comment]
好的。

我们对C#语言不熟，但是我们可以尝试学一下。

**Comment by sennpang** [comment]
> _No description provided._
`HttpClient client = new();

// 创建要发送的文件路径和其他参数
string filePath = "GSF.apk";


var fileName = Path.GetFileName(filePath);
var multipartForm = new MultipartFormDataContent($"-----{Guid.NewGuid()}");
var streamContent = new StreamContent(File.OpenRead(filePath));
multipartForm.Add(new StringContent((string)tokenInfo["data"]["params"]["signature"]), "\"signature\"");
multipartForm.Add(new StringContent((string)tokenInfo["data"]["params"]["x-cos-security-token"]), "\"x-cos-security-token\"");
multipartForm.Add(new StringContent((string)tokenInfo["data"]["params"]["key"]), "\"key\"");

multipartForm.Add(streamContent, "file", fileName);

//修饰boundary，移除双引号
dynamic boundary = multipartForm.Headers.ContentType.Parameters.First(o => o.Name == "boundary");
boundary.Value = boundary.Value.Replace("\"", String.Empty);

var rsp = await client.PostAsync((string)tokenInfo["data"]["endpoint"], multipartForm);
var content = await rsp.Content.ReadAsStringAsync();`

**Comment by sennpang** [comment]
> _No description provided._
直传文件这里需要处理下
[dotnet.txt](https://github.com/PGYER/upload-app-api-example/files/15285771/dotnet.txt)
