### ISSUE TITLE
shell脚本 最近这两周开始上传不成功

### ISSUE THREAD

**Issue by NoahZJY** [PGYER/upload-app-api-example#34]
<img width="1040" alt="image" src="https://github.com/user-attachments/assets/af6c886a-e9e5-461c-818f-57adf3a695e6">

**Comment by shishirui** [comment]
我们这边测试后发现是正常的。

从你的log中看到，脚本是在上传最后一步出错了。你可以尝试把`curl`后面的`-s`去掉，然后单独执行一下看看出现什么错误，然后根据提示的错误有针对性的去解决。

**Comment by NoahZJY** [comment]
> 我们这边测试后发现是正常的。
> 
> 从你的log中看到，脚本是在上传最后一步出错了。你可以尝试把`curl`后面的`-s`去掉，然后单独执行一下看看出现什么错误，然后根据提示的错误有针对性的去解决。

你好 ，我这边看了是token获取的endpoint无法连接，请问是什么情况呢
curl: (28) Failed to connect to pgy-apps-1251724549.cos.accelerate.myqcloud.com port 443 after 75084 ms: Couldn't connect to server
