### ISSUE TITLE
windows上传apk脚本如何写

### ISSUE THREAD

**Issue by Mxrgod** [PGYER/upload-app-api-example#8]
windows上传apk脚本如何写

**Comment by shishirui** [comment]
可以先安装 Git Bash，让 windows 具备 shell 的执行环境。然后可以使用我们的 shell 上传脚本： https://github.com/PGYER/pgyer_api_example/tree/main/shell-demo

**Comment by Mxrgod** [comment]
是在windows安装git用git-ci来执行脚本吗？？

**Comment by Mxrgod** [comment]
> @shishirui 
是在windows安装git用git-ci来执行脚本吗？？

**Comment by shishirui** [comment]
https://www.cnblogs.com/woods1815/p/11026658.html
参考下这个教程 @Mxrgod

**Comment by Mxrgod** [comment]
> https://www.cnblogs.com/woods1815/p/11026658.html 参考下这个教程 @Mxrgod

@shishirui 
如果这个个流程要用git-ci进行自动化处理，也是这样吗？？

**Comment by shishirui** [comment]
不太清楚你说的 git-ci 是什么环境。总之，只要能执行 shell 的环境都可以

**Comment by Mxrgod** [comment]
> 不太清楚你说的 git-ci 是什么环境。总之，只要能执行 shell 的环境都可以

@shishirui 就是我们现在的app打包，然后上传蒲公英都是通过gitlab-ci/cd流程来进行的，windows下我们都是写了bat批处理脚本让gitlab-runner调用执行脚本的

**Comment by shishirui** [comment]
如果是 gitlab的ci/cd 那肯定是可以的。你就把之前上传的app地方，改成直接调用 pgyer-upload.sh 脚本应该就是可以的

**Comment by Mxrgod** [comment]
> 如果是 gitlab的ci/cd 那肯定是可以的。你就把之前上传的app地方，改成直接调用 pgyer-upload.sh 脚本应该就是可以的

@shishirui 好像不行的吧，你们测试过吗？识别不了里面的一些命令之类的

**Comment by shishirui** [comment]
> > 如果是 gitlab的ci/cd 那肯定是可以的。你就把之前上传的app地方，改成直接调用 pgyer-upload.sh 脚本应该就是可以的
> 
> @shishirui 好像不行的吧，你们测试过吗？识别不了里面的一些命令之类的

你的 gitlab 是安装在本地 windows 上吗？还是安装在还是远程 linux 服务器上？

**Comment by Mxrgod** [comment]
> > > 如果是 gitlab的ci/cd 那肯定是可以的。你就把之前上传的app地方，改成直接调用 pgyer-upload.sh 脚本应该就是可以的
> > 
> > 
> > @shishirui 好像不行的吧，你们测试过吗？识别不了里面的一些命令之类的
> 
> 你的 gitlab 是安装在本地 windows 上吗？还是安装在还是远程 linux 服务器上？

@shishirui 我们的gitlab-runner是安装一台远程的windows虚拟机上的

**Comment by shishirui** [comment]
> > > > 如果是 gitlab的ci/cd 那肯定是可以的。你就把之前上传的app地方，改成直接调用 pgyer-upload.sh 脚本应该就是可以的
> > > 
> > > 
> > > @shishirui 好像不行的吧，你们测试过吗？识别不了里面的一些命令之类的
> > 
> > 
> > 你的 gitlab 是安装在本地 windows 上吗？还是安装在还是远程 linux 服务器上？
> 
> @shishirui 我们的gitlab-runner是安装一台远程的windows虚拟机上的

我刚自然的以为你的 gitlab 应该是在远程 linux 上的。如果你在 windows 上，那可能是运行不了 shell 文件（因为 shell 需要 linux 的 bash 环境而你没有）。我没用过 windows 上的 gitlab，但刚网上搜了一下好像是 powershell 环境 (https://docs.gitlab.com/runner/shells/) 。如果是这样的话，建议你可以根据我的 shell 脚本简单写一个 powershell 版本的上传脚本。如果你没时间，我近期也可以帮你写一个。

**Comment by Mxrgod** [comment]
> > > > > 如果是 gitlab的ci/cd 那肯定是可以的。你就把之前上传的app地方，改成直接调用 pgyer-upload.sh 脚本应该就是可以的
> > > > 
> > > > 
> > > > @shishirui 好像不行的吧，你们测试过吗？识别不了里面的一些命令之类的
> > > 
> > > 
> > > 你的 gitlab 是安装在本地 windows 上吗？还是安装在还是远程 linux 服务器上？
> > 
> > 
> > @shishirui 我们的gitlab-runner是安装一台远程的windows虚拟机上的
> 
> 我刚自然的以为你的 gitlab 应该是在远程 linux 上的。如果你在 windows 上，那可能是运行不了 shell 文件（因为 shell 需要 linux 的 bash 环境而你没有）。我没用过 windows 上的 gitlab，但刚网上搜了一下好像是 powershell 环境 (https://docs.gitlab.com/runner/shells/) 。如果是这样的话，建议你可以根据我的 shell 脚本简单写一个 powershell 版本的上传脚本。如果你没时间，我近期也可以帮你写一个。

@shishirui 我也在尝试去写，是遇到一些问题，所以才想请教一下您这是不是有windows的方法，还请帮忙写写吧，我也继续尝试一下，谢谢

**Comment by shishirui** [comment]
好的

**Comment by shishirui** [comment]
我找到了一种方法，亲测有效，你也可以试试（我的环境是windows10）：

1. 首先安装 git bash，让你的 windows 具备 bash 环境
2. 以`bash.exe`来执行 `pgyer_upload.sh` 脚本

命令如下：

    D:\> & 'C:\Program Files\Git\bin\bash.exe' .\pgyer_upload.sh <your-pgyer-api-key> <your-ipa-or-apk-file>

完成后，就会直接返回具体的的App信息。

因此，如果你用的是 Gitlab 的 CI/CD 环境，那么直接把以上命令放到你的持续集成脚本中（应该是 `.gitlab-ci.yml`），应该就可以了。
 
@Mxrgod

**Comment by Mxrgod** [comment]
> 
@shishirui 好的，我试试看，谢谢
